apiVersion: v1
kind: Service
metadata:
  annotations: 
    metallb.universe.tf/allow-shared-ip: shared
  name: ftps
  labels:
    app: ftps
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
  - name: ftps
    port: 21
  - name: ftp
    port: 20
  - name: pasv
    port: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  strategy: 
    type: Recreate
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
        - name: ftps
          image: service_ftps
          imagePullPolicy: Never
          ports:
          - containerPort: 20
            name: ftp
          - containerPort: 21
            name: ftps
          - containerPort: 30000
            name: pasv