apiVersion: v1
kind: Service
metadata:
  annotations: 
    metallb.universe.tf/allow-shared-ip: shared
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  selector:
    app: phpmyadmin
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: service_pma
          imagePullPolicy: Never
          ports:
          - containerPort: 5000