apiVersion: v1
kind: Service
metadata:
  annotations: 
    metallb.universe.tf/allow-shared-ip: shared
  name: grafana
  labels:
    app: grafana
spec:
  type: LoadBalancer
  selector:
    app: grafana
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - image: service_graf
        name: grafana
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          name: grafana
      